### ISSUE TITLE
Feature proposal: default price storage

### ISSUE THREAD

**Issue by ninichat** [esge/PoE-HarvestVendor#11]
Storing a default price for a craft category in a json file (or something else, not sure if there's a better way with ahk for easy data persistence).
This default price could be saved when the user clicks on Create posting (ignoring the craft level).

And when the user next uses "Add craft" it would check if there is a default price for the craft category, and pre-fill the box.
Let me know what you think about this :)

**Comment by esge** [comment]
yes, this is something that i plan to do, although not sure how soon.
some other ppl on TFT are also working on some price aggregator so we maybe can plug data from that in, we'll see

**Comment by esge** [comment]
price storage will be in next release
