### ISSUE TITLE
Random numbers and alphabets

### ISSUE THREAD

**Issue by Meikorawr** [esge/PoE-HarvestVendor#17]
The program picks up and adds the most random alphabets and numbers.
![image](https://user-images.githubusercontent.com/78977351/107804259-a545af80-6d9e-11eb-8984-6b825f6c4201.png)

**Comment by esge** [comment]
this happens when you select too much, this is the area you want
https://github.com/esge/PoE-HarvestVendor/blob/master/examples/example3.png?raw=true

also working on overall improvement to the random chars problem

**Comment by Meikorawr** [comment]
Tested with the selection area changes and can confirm it works properly when there is only text.
