### ISSUE TITLE
remove non-X/ add X being recognized as remove X/add X

### ISSUE THREAD

**Issue by Arecurius0** [esge/PoE-HarvestVendor#19]
with version 0.24 (i think) everything was fine but after updating to 0.3 remove non-X/add X is being recognized as remove X/add X which can lead to bricked items if people dont pay attention to the output and craft later on

**Comment by Arecurius0** [comment]
tested out today again with 0.3 and  appears to be working fine. Suspicion: F.lux (screencolour altering software adapting to daytime) might have caused this or something was overlapping on screen that i did not notice

**Comment by esge** [comment]
it is for sure a problem

**Comment by esge** [comment]
fixed in 0.3.1
