### ISSUE TITLE
Error at line 760.

### ISSUE THREAD

**Issue by CrazylikE** [esge/PoE-HarvestVendor#20]
Line Text: switch group {
Error: This line does not contain a recognized action.

The problem will exit.

**Comment by CrazylikE** [comment]
Reading other issues, this seems to be fixed by updating AHK. Will try that the next time I've shut all my scripts down I guess.

**Comment by esge** [comment]
yes there is a problem with processing switch case in recent AHK versions, needs update to 1.1.33.02

**Comment by esge** [comment]
this will be fixed in next release(0.4.2), i rewrote the parts that required the broken funcitonality to not require it
