### ISSUE TITLE
Confusing "lv" indicator near the craft name

### ISSUE THREAD

**Issue by bananashot** [esge/PoE-HarvestVendor#21]
Hey, this is not an issue but rather an enhancement request, currently, the craft name goes like - (1x) [Enchant Weapon: Elemental Damage][lv82]  < 10c >

lv82 may be really confusing here; thus, you may need to change the phrasing to something like seed level or change the level phrase to the level of the items to which the craft can be applied (i.e lv 100 for all seeds 76+)

**Comment by esge** [comment]
right now its just the same level as shown in the harvest interface, but i agree and i do plan on make it just show 76+ if its above that

**Comment by esge** [comment]
changed it to show just 76+ for 76 and above
will be in next release
