### ISSUE TITLE
Can't add crafts

### ISSUE THREAD

**Issue by Vikingenq** [esge/PoE-HarvestVendor#31]
It was working in 0.4.3, after downloading new version (0.4.4) i can't add crafts.

Im clicking "add crafts", marks crafts i want to sell (all i've got atm) and after "Please wait" none of the crafts show off in the window.

Crafts im talking about - reforge keep pref lucky, aug def, fracture prefix 1/3 so definetly not ignored by you.
yes i've got newest ahk and Capture2Text.
yes i tried many times reseting .ahk, readding crafts and changing some settings like league, monitor, clearing and adding etc.

**Comment by esge** [comment]
are you selecting also the seed icons on the left side? (its recommended not to)
and if not, can you provide whats in temp.txt after capture ?

**Comment by Vikingenq** [comment]
I'd like to provide, but its crystal clear, nothing showed in after capture so can't even upload empty files, tried hotkey ctrl + G and by "add craft" in window.

Tried with seed icons(on older versions i was always selecting seed icons, worked all time but good to know) and without, same results - "Please wait" and pops up empty window. 

Vikingen#5154 Can show on stream, provide screenshots anything you want.

**Comment by esge** [comment]
solved "in person" by the magic of restating it 6 times ¯\_(ツ)_/¯
