### ISSUE TITLE
Add option for unformated crafts

### ISSUE THREAD

**Issue by AgentService** [esge/PoE-HarvestVendor#32]
Since when you search for crafts over ctrl + f it will not highlight formatted text.
So an option to allow an "unformated" sell string would be nice.

Thx

**Comment by esge** [comment]
the formatting is agreed upon with TFT mods, and they vetoed the style

**Comment by AgentService** [comment]
ok. 
Maybe reconsider it. On big lists its very hard to find the craft you lookin for.
only the string parts which ppl actually search for could be out of formatting? If thats even possible to do in inLine.

**Comment by esge** [comment]
add a format where highlight works
