### ISSUE TITLE
[Request] Add "Ignore lvl of craft" option

### ISSUE THREAD

**Issue by MaelKoT** [esge/PoE-HarvestVendor#34]
HarvestVendor is not able to correctly determine craft levels, so why not add an option to ignore it?
In endgame content / t14-16 maps, all crafts are level 81+; and those who farm low-level maps may simply not use this setting.

**Comment by MaelKoT** [comment]
This will also may shorten length of the lines so that everything does not look like in image 1.
![image](https://user-images.githubusercontent.com/2527033/108342923-67a4b480-71ec-11eb-8338-104721ef363b.png)

**Comment by esge** [comment]
lvl76+ has been done because lvl76 is all you need for any items/mods up to ilvl100
this will be changed in next release to just show the level as is in the horti station because many people don't know this and have been complaining

**Comment by MaelKoT** [comment]
Wow, I didn't know that either =_=

Anyway, this still can shorten the length of the lines :)

**Comment by esge** [comment]
trust me, you want the lvl info there cos ppl dont want to bother to ask you what level it is to know if it works for their item, and they wont automatically assume that no lvl = high enough

**Comment by MaelKoT** [comment]
What about thousands and thousands of discord messages without specifying the level of crafting? No one ever even thinks about the craft lvl, when they see a message. If lvl is not indicated there, then it is enough for any craft. And IF it is indicated, that means this is some kind of low-level craft ...

**Comment by carloverso** [comment]
Also, if no price provided, can we not show <>? Here's my reasoning: I can't bother researching craft prices and people who buy them, just offers the price anyway if it's too high.

**Comment by MaelKoT** [comment]
Sadge :(

**Comment by rushtothesun** [comment]
> 
> 
> Sadge :(

Since for whatever reason the dev doesn't want to do this use the AHK version and go to line 1212 which has:
`outString .= "   ``" . count . "x ``**``" . craftNoLvl . "``**``" . mySpaces . "[" . craftLvl . "]" `

change it to
`outString .= "   ``" . count . "x ``**``" . craftNoLvl . "``**``" . mySpaces`

The gui will still have lv on it but when you click "Create Posting" the level will be removed
