### ISSUE TITLE
How to remove those space between the "item" and "item level

### ISSUE THREAD

**Issue by Elezen514** [esge/PoE-HarvestVendor#36]
![image](https://user-images.githubusercontent.com/59316216/108585345-1264c200-7316-11eb-916f-29a3f66a5ee6.png)
As you can see in the picture is there a way to edit that..?

**Comment by esge** [comment]
it was intentional formatting change to align levels and price
the only way is manual edit of the  message or editing the code

**Comment by Elezen514** [comment]
Alright thank you
