### ISSUE TITLE
WANT  [create posting for all ]button

### ISSUE THREAD

**Issue by giveyousomecolorlooklook** [esge/PoE-HarvestVendor#39]
I want to sell craft in TFT AND In path of exile Trading,but  crafts  is not divided into diffent catagory in  path of exile Trading.
So i think i need a  [create posting for all ]button.

**Comment by esge** [comment]
i'm in agreement with TFT discord to optimize for them.
there is a post all button that is activated when you select a Standard league, you can use that and manually edit the league in the message before sending it to discord
