### ISSUE TITLE
[REQUEST] Pressing Esc while in capture mode to stop it

### ISSUE THREAD

**Issue by tgrange42** [esge/PoE-HarvestVendor#42]
It would prevent the research, saving time. It may be on Esc press or on right click

**Comment by esge** [comment]
yeah, i dont have a fix for making esc cancel it, but if you just click instead of drag select it will end caputre and read nothing cos there is no area to parse

**Comment by esge** [comment]
looks good, i'll test it a bit, will be in the next release
