### ISSUE TITLE
[SOLVED] Line 1506

### ISSUE THREAD

**Issue by PredySvK** [esge/PoE-HarvestVendor#49]
I have this error, yesterday it worked great. I tried update/reinstall without help. Thank for any help.
![Snímka](https://user-images.githubusercontent.com/81490028/112734136-3f734880-8f44-11eb-8cca-f8cdfc7f3a4d.PNG)

**Comment by esge** [comment]
did you accidentally set the scale in settings to 0 or nothing. or maybe use comma instead of dot for decimal, or other way around.

**Comment by PredySvK** [comment]
I used comma, there was problem. Thanks a lot :)
