### ISSUE TITLE
Enchant a non-Unique Map with "Map doesn't consume Sextant charges"

### ISSUE THREAD

**Issue by Aradiv** [esge/PoE-HarvestVendor#50]
This craft is essential for fractured map farming so it shouldn't be 
ignored.

**Comment by esge** [comment]
this craft is being processed, if not, its a failure of the text recognition.
it outputs: "Enchant Map: no Sextant use"

**Comment by Aradiv** [comment]
okay then the text recognition failed i had it and it wasn't recognized and it is listed in the "ignored crafts list"
