### ISSUE TITLE
Crafts not getting added to Harvest Vendor

### ISSUE THREAD

**Issue by DeckStarg** [esge/PoE-HarvestVendor#56]
Hi

Some of my crafts are not getting recognised and added to the app to create a post.  Here is a list of 10 crafts in my bench:
1 x Enchant Body Armour: Strength
1 x Reforge Normal or Magic: Chaos
1 x Enchant Body Armour: Max Life
1 x Reforge rare: less likely
1 x Reforge rare: more likely
1 x Refogre rare keep suffixes lucky
1 x Enchant Weapon: Weapon range
3 x Reroll Prefix, Suffix and implicits lucky

Out of the 10 crafts, the following were not recognised:
1 x Reforge rare: less likely
1 x Reforge rare: more likely
1 x Enchant Weapon: Weapon range

This is also not the only time the capture does not recognise some crafts.

**Comment by esge** [comment]
could you get me a screenshot of your horticracting station for testing ?

**Comment by DeckStarg** [comment]
Hi there

I have subsequently sold some of the crafts on TFT already but here is what is left.

![image](https://user-images.githubusercontent.com/9691521/128497610-e757eeca-4abf-450b-890d-194e5c48bc4c.png)

**Comment by esge** [comment]
are you selecting also the pictures on the left? that can mess up stuff, this is the optimal area for the grab
https://github.com/esge/PoE-HarvestVendor/raw/master/examples/snapshotArea.png

**Comment by DeckStarg** [comment]
OOOOOOOOOOOOOOOOOOOHHHHHHHHHHHHHHH

That is exactly what I am doing wrong.  Thanks for that.  Sorry for the trouble

**Comment by esge** [comment]
no problem :)
