### ISSUE TITLE
Create Post with "coloured mode in settings" is been blocked in TFT WTS posting => reason WTS is missing

### ISSUE THREAD

**Issue by Onktakh** [esge/PoE-HarvestVendor#57]
Hello, 
thank you for the nice job and Harvestvendor it´s awesome. 
My last posting with the settings I have used all the time got rejected due to the failure message ==> Missing WTS in sale text. Investigating the trade chat i havent seen any other coloured post. Seems it is somehow not working anymore. The uncoloured version was still being posted by others while i need to wait for the 15 minutes counter now. 
![trovebotfailure](https://user-images.githubusercontent.com/59090233/130225587-8d8a14ec-a982-41cf-9bff-8a9d2f9201ee.png)

**Comment by esge** [comment]
i'll look into that, its weird that it works for other ppl, its more for the discussion with TFT mods about what the bot detects.

**Comment by esge** [comment]
it should be fine now, it was an issue on the side of TFTs bot yesterday
