### ISSUE TITLE
App doesn't recognize legacy rem/add on Standard.

### ISSUE THREAD

**Issue by ximxoo** [esge/PoE-HarvestVendor#60]
Hello. Like in the title. I don't know if it's OCR mistake or PoEHV. 

https://i.gyazo.com/2d06bbcb425fd2d69a9c4242b577246d.jpg

**Comment by esge** [comment]
i dont keep adding to the crafts but only adjust for current league otherwise it would bulk up to be a lot of mess in identifying the crafts over time. sadly this will cause no backwards compatibility
