### ISSUE TITLE
GUI not opening

### ISSUE THREAD

**Issue by Medifri501** [esge/PoE-HarvestVendor#69]
Hi! I'm having issuies with opening gui
The script \ exe (I've tried both) launch without problems
Ctrl+g seems to work fine (I can see new crafts if I use a working version)
But then the gui doesn't open, I can see the window on the taskbar but not open it
![image](https://user-images.githubusercontent.com/60852485/169294271-e81b1afa-9f3d-40ba-86d9-6d92217fd944.png)
The issue appers in any version later than 0.8
0.8 works fine
Thanks for your time =3

**Comment by esge** [comment]
there is a feature that stores window position and sometimes it messes up, if you go to appdata/roaming/PoE-HarvestVendor and delete the lines about last window position in settings.ini, or even whole settings.ini, it should fix it

**Comment by Medifri501** [comment]
Deleting window pos settings worked
Thanks again!
