### ISSUE TITLE
Updating doesn't work?

### ISSUE THREAD

**Issue by candybomberz** [esge/PoE-HarvestVendor#71]
So I've downloaded the newest exe version 4 times,
2 times the non-first-install,
last 2 times the first-install version.

After deleting all folders and downloading it again,
when I start the app,
it still tells me it's 0.8.1b and there is an update on github ...

**Comment by esge** [comment]
oh fuck, thats my bad, it is updated only showing the wrong version number

**Comment by esge** [comment]
i updated the zip files, it should be fine now
